export const errorCodes = {
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  TOURNAMENT_NOT_FOUND: "TOURNAMENT_NOT_FOUND",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  ACHIEVEMENT_NOT_FOUND: "ACHIEVEMENT_NOT_FOUND",
};
